GET http://localhost:8000/

###
GET http://localhost:8000/notfound

###
POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "name": "ekram",
    "email": "ekramullah69@gmail.com",
    "password": "Coc@104035"
}

###
POST http://localhost:8000/api/v1/auth
Content-Type: application/json

{
    "email": "ekramullah69@gmail.com",
    "password": "Coc@104035"
}

###
GET http://localhost:8000/api/v1/reset/verifyEmail/rizwanshuvo@gmail.com

###
GET http://localhost:8000/api/v1/reset/verifyOTP/rizwanshuvo@gmail.com/856385

###
POST http://localhost:8000/api/v1/reset/resetPass
Content-Type: application/json

{
    "email": "rizwanshuvo@gmail.com",
    "otp": "856385",
    "password": "12345678"
}